name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      apk: app/build/outputs/apk/release/app-release-unsigned.apk
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: build release 
      run: ./gradlew assembleRelease
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: app/build/outputs
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: pocket-apps/action-setup-firebase@v2
      with:
        firebase-token: ${{secrets.FIREBASE_TOKEN}}
    - name: upload artifact to Firebase App Distribution
      run: firebase appdistribution:distribute ${{ needs.build.outputs.apk }} --token ${{secrets.FIREBASE_TOKEN}} --app ${{secrets.FIREBASE_APP_ID}} --groups "trusted-testers" --release-notes "Release server"
